# Site settings
title: "moofy.org"
domain: moofy.org
baseurl: "/"
url: "https://moofy.org"
github_source_link: "https://github.com/mufaro3/mufaro3.github.io"
  
# messages of the day
motds: [  
  # 1984
  'WAR IS PEACE!',
  'IGNORANCE IS STRENGTH!',
  'FREEDOM IS SLAVERY!'
]

footer_quotes: [
  # nirvana
  "Forever in debt to your priceless advice"
]

# Personal Information
public_email: 'mail <span class="normal">at</span> moofy <span class="normal">dot</span> org'
github: 'mufaro3'
  
# Blog Settings

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
permalink: /posts/:title/
safe: false
