# Site settings
title: "nickelulz.xyz"
footer_message: "close the world, open the next"
domain: nickelulz.github.io
baseurl: "/"
url: "https://nickelulz.github.io"

# Personal Information
username: "nickelulz"
public_email: "nickelulz@proton.me"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
