# Site settings
title: "nickelulz.xyz"
domain: nickelulz.github.io
baseurl: "/"
url: "https://nickelulz.xyz"

# messages of the day
motds: [ 
  'big tech is literally hitler', 
  'god bless templeOS',
  'all hail Terry Davis',
  '<span class="mono anti-highlight fs-normal">01001100 01000001 01011001 01000101 01010010 00100000 00110000 00110001</span>',
  'WAR IS PEACE!'
]

footer_quotes: [
  "no matter how real the wired is, the real world will always be more real",
  "let's all love lain!",
  "close the world, open the next",
  "you are now, officially, a member of the knights of the lambda calculus!"
]

# Personal Information
username: "nickelulz"
public_email: 'nickelulz <span class="normal">at</span> proton <span class="normal">dot</span> me'
github: "nickelulz"
instagram: "@notnickelulz"
steam: "nicklesidk"
discord: "nickelulz"

# Blog Settings

# Build settings
markdown: kramdown
permalink: /:categories/:title/
safe: false
