# Site settings
title: "nickelulz.xyz"
domain: nickelulz.github.io
baseurl: "/"
url: "https://nickelulz.xyz"
guestbook_url: "http://users.smartgb.com/g/g.php?a=s&i=g19-01585-99" 

# messages of the day
motds: [ 
  # >le hacker 4chan
  # '<code>rm -rf /</code>', 
  # 'delete System32',
  
  # sucking terry davis' penis
  # 'god bless templeOS',
  # 'all hail Terry Davis',
  
  # 1984
  'WAR IS PEACE!',
  'IGNORANCE IS STRENGTH!',
  'FREEDOM IS SLAVERY!'
]

footer_quotes: [
  # lain quotes
  "no matter how real the wired is, the real world will always be more real",
  "let's all love lain!",
  "close the world, open the next",
  
  # >le hacker 4chan
  "<code>(format t \"</code>Welcome to the Knights of the Î»-Calculus!<code>\")</code>",
  "smoke crack and install gentoo :)",

  # radiohead references
  "\"that's it, sir? you're leaving?\"",
  "fifteen steps .. and then a sheer drop",

  # the smiths
  "Please excuse me from gym. I have a terrible cold coming on."
]

# Current Read
current_read_name: "Julius Caesar"
current_read_author: "William Shakespeare"

# Personal Information
username: "nickelulz"
public_email: 'nickelulz <span class="normal">at</span> proton <span class="normal">dot</span> me'
github: "nickelulz"
instagram: "@notnickelulz"
steam: "nickel"
discord: "nickelulz"

# Blog Settings

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
permalink: /posts/:title/
safe: false
